name: Ping other repos

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        if: ${{ github.repository == 'mdn/browser-compat-data' }}
        with:
          token: ${{ secrets.SIDESHOWBARKER }}
          repository: w3c/mdn-spec-links
          event-type: ping
          client-payload: '{"repository": "${{ github.repository }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
